#include <string>
#include "quefacemos.h"
#include "quefacemos2.h"
#include "quefacemos3.h"
#include "quefacemos4.h"
#include "quefacemos5.h"
//#include "quefacemos6.h"
//#include "quefacemos7.h"
//#include "quefacemos8.h"
//#include "quefacemos9.h"
//#include "quefacemos10.h"
//#include "quefacemos11.h"
//#include "quefacemos12.h"
//#include "quefacemos13.h"
//#include "quefacemos14.h"
//#include "quefacemos15.h"
//#include "quefacemos16.h"
//#include "quefacemos17.h"
//#include "quefacemos18.h"
//#include "quefacemos19.h"
//#include "quefacemos20.h"
//#include "quefacemos21.h"
//#include "quefacemos22.h"
//#include "quefacemos23.h"
//#include "quefacemos24.h"
//#include "quefacemos25.h"
//#include "quefacemos27.h"

int main() {

}